config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new', as: 'signup'
  get '/home', to: 'staticpages#home', as: 'home'
  get '/help', to: 'staticpages#help', as: 'help'
  get '/contact', to: 'staticpages#contact', as: 'contact'
  root "staticpages#home"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 20}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                        format: {with: VALID_EMAIL_REGEX}, 
                        length: { maximum: 255 },
                        uniqueness: true
    validates :password, presence: true, 
                        length: { minimum: 6 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello    
        render html: "hello, world!"  
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    # debugger
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the simple App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(title = '')
        base_title = "The simple app"
        if title.empty?
            base_title
        else
            title + " | " + base_title
        end
    end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user)
        gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= full_title(yield(:title))  %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= debug(params) if Rails.env.development? %>
</head>

<body>
    <div class="container">
        <%= render  "partials/navbar" %>
        <%= yield %>
        <%= render  "partials/footer" %>
    </div>
</body>

</html>

app/views/partials/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="#">Ruby on Rails Tutorial</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="#">News</a></li>
        </ul>
    </nav>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to  "Home", home_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Help", help_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Contact", contact_path, :class=>"nav-link" %>
            </li>
        </ul>
    </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/staticpages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Conact page</h1>

app/views/staticpages/help.html.erb
<h1>Help</h1>

app/views/staticpages/home.html.erb
<% provide(:title, "home") %>
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <%= link_to  "Sign up now!", signup_path, :class=>'btn btn-primary'%>
</div>

<%= image_tag  "cat.jpg", :class=>'yo' %>

app/views/staticpages/skalippan.html.erb
<h1> <%= @name %> pages </h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center my-3">Sign up</h1>

<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, :class => "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, :class => "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :class => "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% flash.each do |k, v| %>
  <div class="alert alert-<%= k %>"><%= v %></div>
<% end %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
       <h1>
         <%= gravatar_for @user %>
         <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>